### ISSUE TITLE
non-root user cannot login

### ISSUE THREAD

**Issue by xingyong** [pingcap/tidb-dashboard#1010]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

 34 func (a *Authenticator) Authenticate(f user.AuthenticateForm) (*utils.SessionUser, error) {
 35   // Currently we don't support privileges, so only root user is allowed to sign in.
 36   if f.Username != "root" {
 37     return nil, user.ErrSignInOther.New("non root user is not allowed")
 38   }

**What did you expect to see?**

only root user can login

**What did you see instead?**

all user in tidb could login

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

master

**Comment by unbyte** [comment]
see #985

**Comment by breeswish** [comment]
Hi, non-root sign in is implemented in #985 and will be released with TiDB 5.3.
