### ISSUE TITLE
Confusion in TiDB Cluster System Report

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb-dashboard#1022]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The Diagnosis Result part in the TiDB Cluster System Report contains the diagnosis information both from the selected time period and the current system, which will easily cause confusion of understanding and comprehension.

**Describe the feature you'd like:**

It would be better that the Diagnosis Result could be devided into at least two part: 
- The Diagnosis Result for the selected time period, ordered by log timestamp, if applicatable.
- The Diagnosis Result for the current system

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by breeswish** [comment]
Thanks for the report! Since we are now deprecating this feature, which will be substituted by the clinic service, I'm going to close this issue. If you have questions, feel free to leave comments.
