### ISSUE TITLE
Update auto release script

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb-dashboard#1034]
## Feature Request

**Is your feature request related to a problem? Please describe:**

[PD](https://github.com/tikv/pd) no longer accepts PRs that do not ref issues in the commit message.

**Describe the feature you'd like:**

We could modify the release script to include `ref #4257` in the commit message. This makes it clear that what problem does the PR solve.

As an example, https://github.com/tikv/pd/pull/4253 shows that this kind of message works.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by shhdgit** [comment]
Resolved by https://github.com/pingcap/tidb-dashboard/pull/1054, https://github.com/pingcap/tidb-dashboard/pull/1133.
