### ISSUE TITLE
TiKV instances cannot be viewed after Profile

### ISSUE THREAD

**Issue by HunDunDM** [pingcap/tidb-dashboard#1072]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

* Profile PD
* Cluster Info

**What did you expect to see?**

**What did you see instead?**

![image](https://user-images.githubusercontent.com/19789302/143531765-9e1d2fd3-c810-42c5-b8c3-acbf51ebbff8.png)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

PD v5.2.2

**Comment by breeswish** [comment]
Note: this is caused by PD header incorrectly polluted by "WithBeforeRequest".

**Comment by shhdgit** [comment]
Fixed PR: https://github.com/pingcap/tidb-dashboard/pull/1069.
