### ISSUE TITLE
Connection leak during sending request to PD

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-dashboard#1086]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

https://github.com/pingcap/tidb-dashboard/blob/568d528ce8062ae72aa388f8c7f184b0a0cf2ccd/pkg/pd/client.go#L77-L83

The response should be closed in `SendGetRequest`

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

master

**Comment by breeswish** [comment]
@Yisaer Thanks for the report! The response is closed in `res.Body()`:

```go
func (r *Response) Body() ([]byte, error) {
	defer r.Response.Body.Close()
	return ioutil.ReadAll(r.Response.Body)
}
```

Did you find goroutine leaks caused by TiDB Dashboard? It would be great if goroutine pprof can be shared in this case :)

**Comment by Yisaer** [comment]
Thanks for pointing it out. The "bug" is founded during we investigated connection leak problems at first glance.
