### ISSUE TITLE
Large tables and  wide columns  take up too much memory

### ISSUE THREAD

**Issue by Anniegaosuzhen** [pingcap/tidb-dashboard#1097]
## Bug Report

The database has more than 10,000 tables and each table has more than 400 columns. Tidb memory usage monitored by grafana. The memory of TiDB server used too much. As shown below. 
![This is an image](https://github.com/Anniegaosuzhen/helloworld/blob/master/dashboard1.jpeg?raw=true)

**What did you do?**

Creates 10,000 tables, each with 400 columns in TiDB. And the key visualizer function of tidb dashbord is turned on. This feature is turned on by default. After a period of time, the memory is up to 32GB.

**What did you see instead?**

Turn off the key visualizer feature of the tidb dashboard. Memory drops. https://docs.pingcap.com/zh/tidb/stable/dashboard-key-visualizer

![This is an image](https://github.com/Anniegaosuzhen/helloworld/blob/master/dashboard2.jpeg?raw=true)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**
5.2.3

**Comment by breeswish** [comment]
Thanks for the report! I will mark this as a duplication with https://github.com/pingcap/tidb-dashboard/issues/1097.
