### ISSUE TITLE
dashboard sql statement tab,using  slider to choose custom datetime is difficult

### ISSUE THREAD

**Issue by lipingmu101** [pingcap/tidb-dashboard#1143]
dashboard sql statement tab,using  slider to choose custom datetime
is difficult, better to use datetime picker,same as slow_query tab.
![image](https://user-images.githubusercontent.com/90099657/149716480-b0e7847f-2aae-4bca-be51-c8c658fce7bc.png)

**Comment by breeswish** [comment]
Thanks a lot for the report. We have some plans to improve it. We will update this issue when improvements are ready.
