### ISSUE TITLE
Support memory usage information in slow query list page

### ISSUE THREAD

**Issue by pcqz** [pingcap/tidb-dashboard#1195]
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://asktug.com/t/topic/575174

**Describe the feature you'd like:**
![image](https://user-images.githubusercontent.com/45614653/157816254-c28d5f6c-784b-47f6-ae52-ec3cc3e126cf.png)

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by shhdgit** [comment]
Fixed in https://github.com/pingcap/tidb-dashboard/pull/1150.
