### ISSUE TITLE
SQL statement not available

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tidb-dashboard#1203]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

After scrolling down, SQL statement the content disappears

![jWDv9NKRhe](https://user-images.githubusercontent.com/11624213/161016223-e0e09b7c-1931-41f7-837d-41b503f0e8d4.png)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

PD version：6.0 
942b6422c2329d91f0fefa0cff17e27791a5ad3f

**Comment by breeswish** [comment]
Fixed in #1204. Thanks for the report!
