### ISSUE TITLE
Release build must reload cache manually to work

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb-dashboard#1206]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

Load TiDB Dashboard webpage.

**What did you expect to see?**

It works.

**What did you see instead?**

It will fail to work due to cache is not forced to invalidate in the latest HTML:

```html
    <link rel="stylesheet" href="/dashboard/dashboardApp.css" />
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <script src="/dashboard/compat.js"></script>
    <div id="dashboard_page_spinner"><div class="dot-flashing"></div></div>
    <div id="root"></div>
    <script type="module" src="/dashboard/dashboardApp.js"></script>
```

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

master

**Comment by baurine** [comment]
Yep, in clinc service ui, I add an extra timestamp to the link, is it ok for dashboard, or maybe it better to calculate its content hash?

```
    <link rel="stylesheet" href="index.css?t=TIME_PLACE_HOLDER" />
  </head>

  <body>
    <div id="root" class="h-full overflow-auto bg-cc-blue-50"></div>
    <script src="index.js?t=TIME_PLACE_HOLDER"></script>
  </body>
```

```
function buildHtml(inputFilename, outputFilename) {
  let result = fs.readFileSync(inputFilename).toString()

  const placeholders = ['TIME_PLACE_HOLDER']
  placeholders.forEach((key) => {
    result = result.replace(new RegExp(key, 'g'), new Date().valueOf())
  })

  fs.writeFileSync(outputFilename, result)
}
```

**Comment by breeswish** [comment]
@baurine It's your turn to decide the engineering part now :) I'm fine as long as it does resolve the issue.

**Comment by shhdgit** [comment]
The content hash is more popular. But considering we're only build the dist on release and not on project deployment, timestamp is not a problem.
