### ISSUE TITLE
Broken redirect URL in TiDB dashboard

### ISSUE THREAD

**Issue by tmuhonkin** [pingcap/tidb-dashboard#1262]
## Bug Report

**What did you do?**

I have enabled SSO through AzureAD OIDC Provider for TiDB dashboard as right in docs
Cluster was installed with **tiup 1.9.5**
Cluster version is 5.4.0

**What did you expect to see?**

Successful login through AzureAD OIDC provider

**What did you see instead?**

Error on dashboard page with message 
```
SSO Sign In Failed
Error: authenticate failed, caused by: SSO is not configured correctly, caused by: oidc: exchange failed, caused by: oauth2: cannot fetch token: 400 Bad Request Response: {"error":"invalid_request","error_description":"AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.\r\nTrace ID: 77725d14-be56-4d9f-aff6-cada194f7400\r\nCorrelation ID: 31463c6d-77c4-46f7-9162-55f5d713136c\r\nTimestamp: 2022-05-17 20:14:21Z","error_codes":[9002327],"timestamp":"2022-05-17 20:14:21Z","trace_id":"77725d14-be56-4d9f-aff6-cada194f7400","correlation_id":"31463c6d-77c4-46f7-9162-55f5d713136c"}
```

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**
v5.4.0

**Comment by breezewish** [comment]
This error is reported by AzureAD. Could you try with instructions in https://stackoverflow.com/questions/61231144/getting-access-tokens-from-postman-tokens-issued-for-the-single-page-applicati ?

**Comment by tmuhonkin** [comment]
Thanks a lot. It helped. I created it as a desktop or mobile application, not as SPA
