### ISSUE TITLE
Ask for detailed infomation about continuous profiling

### ISSUE THREAD

**Issue by XHHHY19S** [pingcap/tidb-dashboard#1279]
## Question

Hello, during the research of the feature of continuous profiling, the official [document](https://docs.pingcap.com/zh/tidb/v6.0/continuous-profiling) mainly explains how to use and [deploy](https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb) this function; however  I have googled or go over the official documentation for some time, detailed information seems to be less than I expected. 

> How

 can I learn more about the implementation details and design concepts? Thanks!

**Comment by baurine** [comment]
hi @XHHHY19S , compared with manual profiling, continuous profiling just helps us profile the instances automatically and periodically, no more magic. You still need extra professional knowledge to analyze the profile data (likes flamegraph).

You can get more details from the backend implementation: https://github.com/pingcap/ng-monitoring/blob/main/component/conprof/contprof.go

**Comment by XHHHY19S** [comment]
> hi @XHHHY19S , compared with manual profiling, continuous profiling just helps us profile the instances automatically and periodically, no more magic. You still need extra professional knowledge to analyze the profile data (likes flamegraph).
> 
> You can get more details from the backend implementation: https://github.com/pingcap/ng-monitoring/blob/main/component/conprof/contprof.go

Thanks for your replying and your advice! According to your replying, in my normal daily work，I have learned about how to analyze the profile data and understood the fundamental knowledge about continuous profiling.  As for this, the major point I want to express is whether there exists a design document about continuous profiling or dashboard in your Official website? like other modules such as tiflash,  I can reference to detailed design document. Thanks!

**Comment by baurine** [comment]
Got, unfortunately, we don't have a public design doc yet.

**Comment by XHHHY19S** [comment]
> Got, unfortunately, we don't have a public design doc yet.

Got it. Thanks for your reply! Hope for detailed design doc about dashboard in the future, it will contribute to our deep research.
