### ISSUE TITLE
make the profile result more readable

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb-dashboard#1401]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Make the profile result more readable

**Describe the feature you'd like:**
https://github.com/pingcap/tidb-dashboard/blob/22ad520874613023b0821dcc8a3853afda3819ea/pkg/apiserver/profiling/pprof.go#L51-L58

I suggest using `/debug/pprof/goroutine?debug=2` for the Goroutine, and using `/debug/pprof/mutex` for the Mutex.
It'll make the profile result more readable 
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lilyjazz** [comment]
@Hawkson-jee PTAL.

**Comment by mornyx** [comment]
Changing from `/goroutine?debug=1` to `/goroutine?debug=2` is simple and reasonable, but changing from `/mutex?debug=1` to `/mutex` changes the data format from readable text to binary protobuf, which will make the current front-end interaction unavailable. Could you please explain why you need to remove the `debug` parameter of `/mutex`?

**Comment by XuHuaiyu** [comment]
Actually, I do forget why I mentioned `mutex` here. 
I test fetching mutex with and without debug, I think the behavior in dasbboard is acceptable .
