### ISSUE TITLE
tidb-dashboard ui 编译时esbuild报错

### ISSUE THREAD

**Issue by sunqiangwei** [pingcap/tidb-dashboard#1457]
## Question
今天在对tidb-dashboard进行编译时，前端总是编译失败，具体报错信息如下：

packages/tidb-dashboard-for-clinic-cloud dev: /root/tidb-dashboard/ui/node_modules/.pnpm/esbuild@0.14.49/node_modules/esbuild/lib/main.j                                                                                                                                s:1337
packages/tidb-dashboard-for-clinic-cloud dev:         return callback(new Error(error), null);
packages/tidb-dashboard-for-clinic-cloud dev:                         ^
packages/tidb-dashboard-for-clinic-cloud dev: Error: The service was stopped: write EPIPE
packages/tidb-dashboard-for-clinic-cloud dev:     at /root/tidb-dashboard/ui/node_modules/.pnpm/esbuild@0.14.49/node_modules/esbuild/lib                                                                                                                                /main.js:1337:25
packages/tidb-dashboard-for-clinic-cloud dev:     at /root/tidb-dashboard/ui/node_modules/.pnpm/esbuild@0.14.49/node_modules/esbuild/lib                                                                                                                                /main.js:666:9
packages/tidb-dashboard-for-clinic-cloud dev:     at afterClose (/root/tidb-dashboard/ui/node_modules/.pnpm/esbuild@0.14.49/node_modules                                                                                                                                /esbuild/lib/main.js:644:7)
packages/tidb-dashboard-for-clinic-cloud dev:     at /root/tidb-dashboard/ui/node_modules/.pnpm/esbuild@0.14.49/node_modules/esbuild/lib                                                                                                                                /main.js:2050:11
packages/tidb-dashboard-for-clinic-cloud dev:     at onwriteError (node:internal/streams/writable:418:3)
packages/tidb-dashboard-for-clinic-cloud dev:     at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
packages/tidb-dashboard-for-clinic-cloud dev: Node.js v18.12.1
packages/tidb-dashboard-for-clinic-cloud dev: [23:57:43] 'esbuild:dev' errored after 54 s
packages/tidb-dashboard-for-clinic-cloud dev: [23:57:43] Error in plugin "gulp-shell"
packages/tidb-dashboard-for-clinic-cloud dev: Message:
packages/tidb-dashboard-for-clinic-cloud dev:     Command `NODE_ENV=development node builder.js` failed with exit code 1
packages/tidb-dashboard-for-clinic-cloud dev: [23:57:43] 'dev' errored after 54 s
`

具体的编译步骤如下：
cd ui 
pnpm i 
pnpm dev

请成功编译过的兄弟们，指教指教

**Comment by baurine** [comment]
可能是 node 版本的问题，试试 v16.13.0，这个版本我可以编译成功。

**Comment by Lizhe1228** [comment]
楼主您好，我在编译时也遇到了问题，另外请问在windows下可以进行编译吗，编译的环境有必须的要求吗

**Comment by yang1666204** [comment]
跟楼主相同的步骤，操作系统mac13.2.1 node版本16.13.0
![image](https://github.com/pingcap/tidb-dashboard/assets/62841398/dd4237d0-b553-45a3-b406-ab57ff035c6e)
