### ISSUE TITLE
Deploy the tidb dashboard on the K8S, unable to run

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [pingcap/tidb-dashboard#1461]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

Deploy the tidb dashboard on the K8S, unable to run

Deployed like this：kubectl -n tidb-cluster apply -f tidb-dashboard.yaml

tidb-dashboard.yaml 
···
apiVersion: pingcap.com/v1alpha1
kind: TidbDashboard
metadata:
  name: basic
spec:
  baseImage: pingcap/tidb-dashboard
  version: v6.5.0

  clusters:
    - name: basic

  requests:
    storage: 10Gi
···

**What did you expect to see?**

It operates normally and can be accessed through port 12333

**What did you see instead?**

Unable to run. The logs are as follows：
Fatal glibc error: CPU does not support x86-64-v2

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

···
  baseImage: pingcap/tidb-dashboard
  version: v6.5.0
···

k8s version: v1.22.12

**Comment by SabaPing** [comment]
Please refer to https://asktug.com/t/topic/999530
