### ISSUE TITLE
编译时出现了问题

### ISSUE THREAD

**Issue by Lizhe1228** [pingcap/tidb-dashboard#1463]
## Question
小白想问个问题，我在编译时遇到了以下报错，希望能得到大佬的指点
<img width="691" alt="30c16da96c214aa28c0c835064b0437" src="https://user-images.githubusercontent.com/58848764/211706859-16112678-0cac-49e7-b5af-d32670d14661.png">
我的编译步骤：pnpm i；pnpm dev
我是在Windows下进行编译的，在window编译可以嘛，还是必须需要使用linux环境进行编译呢。

**Comment by baurine** [comment]
Windows 我没有试过，但是 TiDB 集群没法在 windows 上跑起来的，所以还是推荐 Linux 环境哈。

**Comment by Lizhe1228** [comment]
> Windows 我没有试过，但是 TiDB 集群没法在 windows 上跑起来的，所以还是推荐 Linux 环境哈。

好的 谢谢啦

**Comment by Lizhe1228** [comment]
您好，谢谢您之前的回复，对于tidb dashboard这个项目我还有几个问题想请教一下您，希望得到您的回复，若打扰到您，请见谅。问题：这个UI界面下这几个不同的文件夹有什么区别呢，他们直接是什么样的联系呀。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pingcap/tidb-dashboard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 下午4:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pingcap/tidb-dashboard] 编译时出现了问题 (Issue #1463)





 
Windows 我没有试过，但是 TiDB 集群没法在 windows 上跑起来的，所以还是推荐 Linux 环境哈。

**Comment by baurine** [comment]
如架构图所示：https://github.com/pingcap/tidb-dashboard/blob/master/ui/ui_arch.png

我们需要在多个产品中复用 tidb-dashboard 中的功能，比如 Statement / Slow Query / Top SQL / Key Visualizer，所以我们把这些功能封装在 tidb-dashboard-lib 中，以便在多个产品中复用，在不同的产品中对接不同的后端 API 实现。

`tidb-dashboard-for-op` 是用于本地部署的集群，`tidb-dashboard-for-dbaas`, `tidb-dashboard-for-clinic-cloud`, `tidb-dashboard-for-clinic-op` 是用于 PingCAP 其它的产品，比如 tidbcloud, clinic。

`tidb-dashboard-client`, `clinic-client` 是不同的 API 实现。

作为个人开发者，只需要关注 `tidb-dashboard-lib`, `tidb-dashboard-for-op`, `tidb-dashboard-client` 这三个文件夹即可。

**Comment by Lizhe1228** [comment]
好的好的，非常感谢您百忙之中回复我的邮件！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pingcap/tidb-dashboard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月17日(星期二) 上午9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pingcap/tidb-dashboard] 编译时出现了问题 (Issue #1463)





 
如架构图所示：https://github.com/pingcap/tidb-dashboard/blob/master/ui/ui_arch.png
 
我们需要在多个产品中复用 tidb-dashboard 中的功能，比如 Statement / Slow Query / Top SQL / Key Visualizer，所以我们把这些功能封装在 tidb-dashboard-lib 中，以便在多个产品中复用，在不同的产品中对接不同的后端 API 实现。
 
tidb-dashboard-for-op 是用于本地部署的集群，tidb-dashboard-for-dbaas, tidb-dashboard-for-clinic-cloud, tidb-dashboard-for-clinic-op 是用于 PingCAP 其它的产品，比如 tidbcloud, clinic。
 
tidb-dashboard-client, clinic-client 是不同的 API 实现。
 
作为个人开发者，只需要关注 tidb-dashboard-lib, tidb-dashboard-for-op, tidb-dashboard-client 这三个文件夹即可。
