### ISSUE TITLE
编译UI时报错 ——An error is reported when compiling the UI

### ISSUE THREAD

**Issue by Lizhe1228** [pingcap/tidb-dashboard#1470]
我在编译UI时，遇到了问题，希望编译成功的朋友能帮我看看，谢谢了。
When I was compiling the UI, I encountered a problem. I hope that friends who have successfully compiled it can help me, thank you.
问题如下
Questions are as follows
<img width="718" alt="ceedb408d1cc59bb8fd810e02b2f977" src="https://user-images.githubusercontent.com/58848764/212902790-7fb6efa9-f4c8-4aee-88f2-3386871b42fb.png">
<img width="721" alt="8e110daa60e8e6c25a92f0fcb853b42" src="https://user-images.githubusercontent.com/58848764/212902813-c5a159dd-abdf-4d0d-ab4c-98e6111f9c3e.png">
<img width="721" alt="84f93ff55cce04000f0a48e14f38db6" src="https://user-images.githubusercontent.com/58848764/212902829-b14c36a3-1629-49de-a534-9caffe996055.png">

**Comment by baurine** [comment]
报错信息提示 `go: command not found`，需要安装一下 golang 哈。

**Comment by Lizhe1228** [comment]
> 报错信息提示 `go: command not found`，需要安装一下 golang 哈。
好的 谢谢！
