### ISSUE TITLE
Can the threshold for slow queries work accurately?

### ISSUE THREAD

**Issue by lilyjazz** [pingcap/tidb-dashboard#1507]
## Question

Confirm the accuracy of slow query threshold, and whether there is any deviation in actual production.
For example, if the default is 300ms, will it only record at 301ms?

**Comment by lilyjazz** [comment]
@mornyx PTAL

**Comment by mornyx** [comment]
The calculation method for cost time is using the native time package in Go. We assume that the `StartTime` recorded in the session is accurate and do not consider the impact of goroutine scheduling on the clock. The margin of error is at the microsecond level and theoretically will not be perceived by our use case.

Ref: https://github.com/pingcap/tidb/blob/master/executor/adapter.go#L1439
