### ISSUE TITLE
The connection of dashboard to TiDB should not be affected by some global variables

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb-dashboard#1604]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**
Some clusters will set global variables like `max_execution_time` to make the database could fail fast queries.

**What did you expect to see?**
Some of these variables should not affect dashboard.

**What did you see instead?**
The slow query page failed to execute, because it exceeded the `max_execution_time`. 
![image](https://github.com/pingcap/tidb-dashboard/assets/4352397/05c275f5-b998-4ef6-a259-f338397efe78)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**
v7.1.1

**Comment by jackysp** [comment]
PTAL @baurine @mornyx

**Comment by jackysp** [comment]
It's better to set `max_execution_time` to 0 when creating the new database session in tidb-dashboard.

**Comment by mornyx** [comment]
Submitted a PR: https://github.com/pingcap/tidb-dashboard/pull/1608.

Setting `max_execution_time` to 0 can be risky (especially if it has been set to a lower value by the customer). So I set it to 60s. Please also help review this value, thanks. cc @baurine
