### ISSUE TITLE
fips: tikv heap profiling failed after enable tls and set require_secure_transport = on 

### ISSUE THREAD

**Issue by mayjiang0203** [pingcap/tidb-dashboard#1613]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

**What did you expect to see?**
No error, works fine.

**What did you see instead?**
Profile Error
failed to fetch and write to temp file: failed to fetch profile with *.prof format: failed to fetch tikv heap profile: Use of uninitialized value $line in substitution (s///) at /dev/stdin line 3323. http://tikv1-peer:20180/debug/pprof/symbol doesn't exist
![image](https://github.com/pingcap/tidb-dashboard/assets/9443637/d12c1e4d-9111-411c-b3ed-bc443abac963)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

master

**Comment by overvenus** [comment]
TiKV heap profile depends on jeprof which does not support mTLS yet.

https://github.com/pingcap/tidb-dashboard/blob/706489ff610dcccc238335b26e0bc97cbf486c6e/pkg/apiserver/profiling/fetcher.go#L78
