### ISSUE TITLE
Cluster info api: dashboard/api/host/all, lack of TiCDC instance information

### ISSUE THREAD

**Issue by Jingyuma** [pingcap/tidb-dashboard#1703]
## Bug Report

There is no TiCDC information when click on cluster info -> disk.
Belows screenshot are from cluster have ticdc deployment.

![image](https://github.com/user-attachments/assets/927b34dd-12dc-4739-a0fc-2f7f1136fc15)
<img width="960" alt="image" src="https://github.com/user-attachments/assets/4a39ded9-de16-49a4-933b-949ace054a86">

**What did you do?**
1. deploy ticdc
2. to go dashboard -> cluster_info -> disk

**What did you expect to see?**

host information with ticdc

**What did you see instead?**
No ticdc information when there are other instance on the host
error message when there is no other instance on the host

real api output:
{
            "host": "xxx7",
            "cpu_info": {
                "arch": "amd64",
                "logical_cores": 8,
                "physical_cores": 4
            },
            "cpu_usage": {
                "idle": 0.99,
                "system": 0.01
            },
            "memory_usage": {
                "used": 2455486464,
                "total": 33298284544
            },
            "partitions": {
              ...
            },
            "instances": {}
        },

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**
v8.1.0

**Comment by baurine** [comment]
fixed by pr #1704
