### ISSUE TITLE
UCP: Avoid screen flash when session is timedout

### ISSUE THREAD

**Issue by breezewish** [pingcap/tidb-dashboard#227]
## Description

When session is not valid, Dashboard will show overview page in an instant, then redirect to sign in page. This "flash" can be improved.

## Score

* 300

## Mentor(s)

* @baurine 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* React
* Axios Library

**Comment by breeswish** [comment]
Still relevant.

**Comment by baurine** [comment]
Still relevant.

**Comment by breezewish** [comment]
The flash screen can be very easily observed in TiDB Cloud.

**Comment by baurine** [comment]
> The flash screen can be very easily observed in TiDB Cloud, or remote environments like AWS.

Got it! let me have a look.
