### ISSUE TITLE
UCP: Support sort time in log search and improve item truncate notification

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb-dashboard#528]
## Description

Although log searching preview only contains first N items, we can still provide sort functionality.

Goals:
- Add browser-side sort to log search
- Modify the notification "displaying first xxx items" to display accurate number, like: "The preview only shows **first** XXX logs (XXX logs in total)." You need to store accurate number in backend.
- Hide the notification if preview number does not exceed.
- Show extra notification when sorting in descending order, like "The preview only shows **first** XXX logs in descending order (XXX logs in total)."

## Score

* 605

## Mentor(s)

* @baurine

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* React

**Comment by baurine** [comment]
Can't continue before #665 is resolved.

**Comment by breeswish** [comment]
Replaced by TiStack. Closing.
