### ISSUE TITLE
Requirement Request: Store (TiKV / TiFlash) Instance Scale-In/Out Progress & ETA

### ISSUE THREAD

**Issue by HunDunDM** [pingcap/tidb-dashboard#570]
## Description

Related project: PD

For instances being scaled-in or scaled-out, display a progress bar of its replica migration.

## Category

* Feature
* Usability

## Value

Scale-In and Scale-Out operation usually takes a very long time to finally finish. Progress is a must. Providing ETA (Estimated time of arrival) is even better.

- Score: 3

## Workload Estimation

20 Person Day

**Comment by breeswish** [comment]
Related: https://github.com/pingcap/pd/issues/2507

**Comment by breeswish** [comment]
Deprecated as a feature unrelated to performance troubleshooting.
