### ISSUE TITLE
Requirement Request: KeyViz: Flow & SQL Statement Integration

### ISSUE THREAD

**Issue by HunDunDM** [pingcap/tidb-dashboard#574]
## Description

Related project: TiDB, TiKV

Now that we have KeyViz and users can know a region is hot. Then what’s next? How to figure out what SQL actually causes the hot read / hot write? A possible solution could be displaying SQLs that read most (if displaying read IO graph) in the bucket. 

Unresolved: How can we count both running and past SQLs for a specific region?

## Category

* Feature
* Usability

## Value

Hotspot is a highly frequent issue. Adapting KeyViz to better support the need to find out hotspots is valuable for our users.

- Score: 4

## Workload Estimation

40 Person Day

**Comment by breeswish** [comment]
@kennytm You may interested in this one.
