### ISSUE TITLE
Requirement Request: add more diagnose rule

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb-dashboard#578]
### backgroud
TiDB 4.0 has introduced the [SQL diagnose](https://pingcap.com/docs-cn/stable/system-tables/system-table-inspection-result/), but only has a little diagnose rule, this Issue want to a add more diagnose rule. 

Here is already some diagnose method but doesn't have related diagnose rule: [TiDB 集群故障诊断](https://pingcap.com/docs-cn/stable/troubleshoot-tidb-cluster/#tidb-%E9%9B%86%E7%BE%A4%E6%95%85%E9%9A%9C%E8%AF%8A%E6%96%AD)

A brainstorm of possible diagnose rules:
- Duplicate / useless indexes (Note: Utilize index hit?)
- New index advice (Note: TiDB is going to implement an index advisor)
- Missing NUMA binding / NUMA binding is incorrect
- Incorrect memory configuration for multi-instance deployment
- SQL plan changed and execution is slowed down notably
- A sql waited too much time
- Potential hotspot
- Reaching thread pool capacity
- OOM
- TiKV panic
- DDL takes too much time?
- Server is busy?
  - RocksDB write stall
  - Scheduler busy
  - Raftstore busy
  - Coprocessor busy / request outdated
- Replica not healthy
- Region not balanced
- PD Scheduler not working caused by reaching disk capacity
- Check sync-log is on
- Some configuration is modified but is not taking effect until restart

## Category

* Feature
* Usability

## Value

This is a highly requested feature in first UCP: https://github.com/pingcap/tidb/issues/14983

- Score: 5

## Workload Estimation

40 Person Day

**Comment by breeswish** [comment]
Covered by the clinic service.
