### ISSUE TITLE
Slow log search result should be cached

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tidb-dashboard#641]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

Search slow log, and click one to see the details. After moving back, it starts search again.

**What did you expect to see?**

Display the result immediately

**What did you see instead?**

Nothing shows up, and the refresh button begin spinning.

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

I'm using v4.0.0 GA, not sure what version is Dashboard.

**Comment by breeswish** [comment]
This is a limitation of the current implementation. Change to a "feature request" instead for this improvement.

**Comment by baurine** [comment]
fixed by #828
