### ISSUE TITLE
Display Total vCore, Memory, etc

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb-dashboard#659]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now user cannot have an overview for overall hardware capacities.

**Describe the feature you'd like:**

We now have a page showing vCores for each host, better to display by instance type (how many total vCore, Memory, ... for TiDB, TiKV, etc) and how many vCores at all. 

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by shenli** [comment]
I suggest showing the CPU type as well. Such as x86, ARM etc. A more complex case is that there are multiple CPU types in a single cluster.

**Comment by breeswish** [comment]
@shenli Arch is not available in current probes, to expose this information we need to modify TiDB, TiKV and PD. Thus I will defer Arch to v4.0.10 ([tracking issue](https://github.com/pingcap/tidb-dashboard/issues/812)). The rest will be shipped in v4.0.9 unchanged.
