### ISSUE TITLE
Use ahooks

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb-dashboard#664]
## Feature Request

**Is your feature request related to a problem? Please describe:**

ahooks is an upgrade for Umi hook

**Describe the feature you'd like:**

Use ahooks: https://ahooks.js.org/docs/umi-hooks-to-ahooks

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by baurine** [comment]
Leave it to UCP.
