### ISSUE TITLE
Support other types of profile and flame graph

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb-dashboard#717]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**
1. dashboard can only output CPU profile, it should also support memory profile, goroutine, trace profile, etc...
2. not only output the flame graph, but also be able to download the original profile documents.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by SunRunAway** [comment]
@crazycs520 @breeswish PTAL

**Comment by breeswish** [comment]
For "profile documents" in 2, could you explain a bit more about its scenario?

**Comment by SunRunAway** [comment]
The tidb developers can profile it with their own go toolchain in their local machine.

**Comment by coocood** [comment]
SVG file lost many information in the original profile samples.

**Comment by youjiali1995** [comment]
What's the progress of this feature? I don't think the default format(graph) of the TiDB profile is easy to use... I prefer to flame graph.

**Comment by breeswish** [comment]
@youjiali1995 @coocood   In latest TiDB Dashboard, there is a debug API feature, that you can download the raw profile data (and other type of pprof endpoints as well). You need to start `go tool pprof` locally to analyze the downloaded raw profile though. Does this fit your need?

**Comment by breeswish** [comment]
@YiniXu9506 Would you like to work on this feature so that the easy-to-use profiling UI can provide more detailed information?

**Comment by coocood** [comment]
> @youjiali1995 @coocood In latest TiDB Dashboard, there is a debug API feature, that you can download the raw profile data (and other type of pprof endpoints as well). You need to start `go tool pprof` locally to analyze the downloaded raw profile though. Does this fit your need?

I think this is sufficient, profile analysis is for advanced users, we don't need to invest too much resource to make the profile UI. The UI just needs to guide the user on how to use the debug.zip file.

**Comment by breeswish** [comment]
This have been implemented in https://github.com/pingcap/tidb-dashboard/pull/1095. It will be available in v5.4.0.
