### ISSUE TITLE
Slow log queries are too slow

### ISSUE THREAD

**Issue by WalterWj** [pingcap/tidb-dashboard#750]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When slow log files are too many, or when queries slow log content is too many, slow log queries are too slow.

**Describe the feature you'd like:**

When slow log files are too many, or when queries slow log content is too many, slow log queries can be faster.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by breeswish** [comment]
@crazycs520 Do we still have this issue?
