### ISSUE TITLE
TiDB Dashboard does not reload the certs automatically after certs renewal

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-dashboard#759]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**
Deploy the TiDB Cluster in Kubernetes, and user cert-manager to manage the certs, before the certs expire, cert-manager will renew the certs automatically.

**What did you expect to see?**
TiDB Dashboard can reload the certs automatically to connect to the TiDB service.

**What did you see instead?**
TiDB Dashboard can not connect to the TiDB service after certs renewal.
```
tidb-cluster-pd-0 pd [2020/09/14 08:39:47.843 +00:00] [WARN] [conn.go:76] ["unknown error occurred while OpenTiDB"] [error="x509: certificate has expired or is not yet valid"]
```

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**
v4.0.5

**Comment by breeswish** [comment]
Hi, we believe that cert renewal is fine, except for the CA certs. Does this fit your case?

**Comment by DanielZhangQD** [comment]
It's OK, thanks!
