### ISSUE TITLE
One-click Flame graph for TiFlash

### ISSUE THREAD

**Issue by zanmato1984** [pingcap/tidb-dashboard#782]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

We would like a one-click solution for TiFlash flame graph generation, like currently what TiKV and TiDB do.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zanmato1984** [comment]
TiFlash API: curl "http://${status_address}/debug/pprof/profile?seconds=${seconds}&frequency=${frequency}"

**Comment by zanmato1984** [comment]
@baurine @breeswish Any updates?

**Comment by breeswish** [comment]
@zanmato1984 Nop, we don't have enough people to start this task in short time. I guess we will start it after v4.0.10.

**Comment by baurine** [comment]
I am trying it.
