### ISSUE TITLE
Cannot login dashboard with tiup playground using a given tidb binary

### ISSUE THREAD

**Issue by zhangysh1995** [pingcap/tidb-dashboard#783]
## Bug Report

**What did you do?**

Log into the dashboard with default user and empty password

**What did you expect to see?**

Login successfully

**What did you see instead?**

Cannot connect to the database

![image](https://user-images.githubusercontent.com/8340592/97560255-62431480-1a19-11eb-931d-c43367acacb1.png)

I could connect to the database via mysql client which means the database server is running, and I saw error in the pd's log:

![image](https://user-images.githubusercontent.com/8340592/97560908-47bd6b00-1a1a-11eb-98fe-e4e76354eecc.png)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

The default one with my tiup

````
xxx:~/.tiup/components/playground/v1.0.8$ tiup playground -version
Found playground newer version:

    The latest version:         v1.2.1
    Local installed version:    v1.0.8
    Update current component:   tiup update playground
    Update all components:      tiup update --all
````

Start the playground with a compiler binary:

````
tiup playground --db 1 --db.binpath ./bin/tidb-server
````

**Comment by breeswish** [comment]
Thanks for the report! I'm unable to reproduce the issue using latest master. Could you provide reproduce steps?

**Comment by breeswish** [comment]
Feel free to leave comments if reproduction is ready. Thanks!
