### ISSUE TITLE
Auto report errors and exceptions

### ISSUE THREAD

**Issue by baurine** [pingcap/tidb-dashboard#784]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, if the dashboard crashes on the user side, we don't know what happened. We need to communicate with the user.

**Describe the feature you'd like:**

Import a tool that could automatically report the errors and exceptions for us, likes [sentry](https://docs.sentry.io/platforms/javascript/)

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by breeswish** [comment]
How about utilizing current Mixpanel tracking?

**Comment by baurine** [comment]
> How about utilizing current Mixpanel tracking?

That's an option, we can try it.

**Comment by breezewish** [comment]
Implemented by #895
