### ISSUE TITLE
Conditional trigger to save related debug data

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb-dashboard#789]
## Feature Request

**Is your feature request related to a problem? Please describe:**

调查问题时，经常会需要故障点更多的 debug 信息，但时间已经过去，拿不到一些现场数据了，例如：

* profile，heap, goroutine ...
* statements_summary 系统表
* processlist 

希望能有一个支持自定义的触发机制，例如当满足以下多个条件或某个条件时，触发自动保存现场数据机制：

* 当某个 digest 的SQL 执行耗时超过一定阈值
* 当 qps 大于某个阈值
* 当 rocksdb 的 cache hit 低于某个阈值
* 当 tidb/tikv 的进程 cpu 超过某个阈值
* 当 tidb/tikv 的进程 mem 超过某个阈值
...

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by breeswish** [comment]
Something similar is a feature that TiDB is implementing: trigger a memory dump when memory exceeds a threshold :)

**Comment by crazycs520** [comment]
Yes, but In TiDB, the condition was so limited, it currently only supports memory threshold check.

The request future is to let the user choose the condition by themself, no mater SQL query or `Prometheus query` will both supported.  And the condition was supported dynamic configured and immediate effect.

**Comment by breeswish** [comment]
I agree. @sunrunaway thoughts?

**Comment by breeswish** [comment]
Note: this is more like a cron job since trigger is not available..

**Comment by breeswish** [comment]
This is now substituted by the continuous profiling.
