### ISSUE TITLE
Support exporting current schema and statistic information in SQL and Statement.

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb-dashboard#797]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Currently, we can use `show create table` and [HTTP API `Export Statistic`](https://docs.pingcap.com/tidb/dev/statistics#export-statistics) to gather this information, 
Even better, we can download them of all tables directly from the SQL page and Statement page with a single click.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by SunRunAway** [comment]
cc @breeswish

**Comment by breeswish** [comment]
There might be a counterintuitive part that the exported statistics and schema is the latest data, while user is very likely to expect getting the related information at that time. Do you have some suggestions about how this can be resolved?

**Comment by SunRunAway** [comment]
There're two requirements 
1. Export current statistics, for diagnosing queries which are happening
2. Export the statistics of this SQL run at the time (https://github.com/pingcap/tidb/issues/18745), for diagnosing queries which happened before.

Before https://github.com/pingcap/tidb/issues/18745 is implemented, only we can do is exporting the current statistics.

**Comment by breeswish** [comment]
We will do this in diagnostics bundle collector.
