### ISSUE TITLE
Store Topology canvas is not fit to full screen

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb-dashboard#801]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

Open store topology page.

**What did you expect to see?**

Store location is rendered without any truncation.

**What did you see instead?**

![image](https://user-images.githubusercontent.com/1916485/99794981-0118e780-2b66-11eb-8161-cea9841823e0.png)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

latest master.

**Comment by unbyte** [comment]
any repro?

**Comment by breeswish** [comment]
@unbyte Just drag the canvas and you will see the graph is being truncated, restricted in a region smaller than the window.

**Comment by baurine** [comment]
Got, will fix it lately.

**Comment by unbyte** [comment]
@baurine actually i've fixed it by setting a min height😂 however i think it's better to make the boundary of canvas more clear
