### ISSUE TITLE
Improve the cost time information display in slow log detail

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb-dashboard#809]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

Currently, the cost time information display is such as below:

![image](https://user-images.githubusercontent.com/26020263/100062616-d7fc9d80-2e6a-11eb-8e4c-3c664056b1ee.png)

The problem is it is hard to understand the relationship of so many durations, maybe we can format such as a tree to easy find out the parent-child relationship:

Currently, the relationship is as below:

```sql

Query_time
    Parse_time
    Compile_time:
        Rewrite_time:
            Process_subquery_time:
        Optimize_time:
    Wait_TS:
    Cop_time:
        Cop_Process_time:
        Cop_Wait_time: 
    Lock_keys_time:
    Local_latch_wait_time:
    Backoff_time:
    Prewrite_time:
    Wait_prewrite_binlog_time:
    Get_Commit_TS:
    Commit_time:
    Commit_backoff_time
    Resolve_lock_time:
Write_Response_time:
Retry_exec_time:

```

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

```sql
▶ bin/tidb-dashboard --version
Internal Version:  nightly
Git Commit Hash:   d03c863267595253c2c39c4007849a4baf63ab0f
UTC Build Time:    2020-11-23 09:57:50

```

**Comment by baurine** [comment]
fixed by #810 , so we can close it.
