### ISSUE TITLE
Frontend cannot compile in ARM

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb-dashboard#826]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In ARM processors the frontend cannot compile.

**Describe the feature you'd like:**

Support compiling in ARM.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by baurine** [comment]
Seems we need an Apple M1 as a test machine 🤔

**Comment by breeswish** [comment]
@baurine The error happens when executing `yarn install`, which will result in Node.js segment fault.

**Comment by unbyte** [comment]
This should be an upstream error.
refs: https://github.com/nodejs/TSC/issues/886, https://github.com/nodejs/build/issues/2474,  https://github.com/nodejs/node/pull/35986
