### ISSUE TITLE
Slow query refresh doesn't work

### ISSUE THREAD

**Issue by baurine** [pingcap/tidb-dashboard#862]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

1. Open slow query page, it is empty first
2. Run `select sleep(1);` in the MySQL client
3. Click the refresh button on the slow query page
4. We can't see the expected slow query

**What did you expect to see?**

We should see a non-empty slow query list with at least one item: `select sleep(1)`

**What did you see instead?**

An empty slow query list

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

master

**Comment by baurine** [comment]
It doesn't reproduce in the master branch with 5.4.0 TiDB.

**Comment by breezewish** [comment]
> It doesn't reproduce in the master branch with 5.4.0 TiDB.

It can be reproduced when 30 minutes is passed.
