### ISSUE TITLE
Statement / slow query export failed in v4.0.10

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb-dashboard#865]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

Export statement or slow query in TiDB Dashboard in TiDB v4.0.10+.

**What did you expect to see?**

Export succeed.

**What did you see instead?**

Export fail.

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

**Comment by breeswish** [comment]
Maybe fixed by https://github.com/pingcap/tidb/pull/22918, needs verify.

**Comment by unbyte** [comment]
works well on v4.0.10+
