### ISSUE TITLE
Error tips: unknown field

### ISSUE THREAD

**Issue by shhdgit** [pingcap/tidb-dashboard#902]
## Bug Report

**What did you do?**

Open slowquery page in dashboard after cluster upgrade.

**What did you expect to see?**

See the slowquery data.

**What did you see instead?**

Error tips without correct data.
- error.api.other: unknown field sql
- error.api.other: unknown field Time

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

v4.0.9

**Comment by shhdgit** [comment]
This is caused by that old column name store in LocalStorage and can be temporarily solved by cleaning up browser's LocalStorage.
![image](https://user-images.githubusercontent.com/11549583/116059253-398f9500-a6b3-11eb-8e34-251e494240ed.png)

**Comment by breeswish** [comment]
As a tip, I think you can record it in our [FAQ](https://docs.pingcap.com/zh/tidb/v4.0/dashboard-faq) and make sure that there is no problem when upgrading to later versions.

**Comment by shhdgit** [comment]
Yeah, I was thinking whether it would be a good option to clean up user preferences after dashboard version change. Or just filter the data by schema.

**Comment by unbyte** [comment]
I believe we can make dashboard automatically handle such a version migration by maintaining version number of local storage schema.
