### ISSUE TITLE
Provide a more powerful log search service

### ISSUE THREAD

**Issue by unbyte** [pingcap/tidb-dashboard#903]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

- support more rules, such as regexp 🤯

- support limiting the record number, topN, botN, desc and so on

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by breeswish** [comment]
Dashboard is now changed to focus on performance troubleshooting. Log search experience can be better delivered by TiStack. Thanks for the suggestion!
