### ISSUE TITLE
Add timezone information along with all timestamp

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb-dashboard#973]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For example: 
1. cluster info
![image](https://user-images.githubusercontent.com/867381/128309294-c6b0ff7d-83fb-4f3e-812b-f7688475388c.png)

2.  SQL statement

![image](https://user-images.githubusercontent.com/867381/128309408-e8f96034-4643-46aa-ba24-68877b168de3.png)

**Describe the feature you'd like:**

Jul 23, 2021 2:24 PM -> Jul 23, 2021 2:24 PM (+08:00)

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by SunRunAway** [comment]
@breeswish

**Comment by breeswish** [comment]
This is a very good suggestion! @shhdgit Would you like to take a look?

**Comment by shhdgit** [comment]
Yeah, sure. Display timezone is useful when communicating and troubleshooting.
