### ISSUE TITLE
The variable data declared in distro.go is not initialized correctly

### ISSUE THREAD

**Issue by s3nt3** [pingcap/tidb-dashboard#975]
## Bug Report

**What did you do?**

I modify the pd's go.mod file with replace statement to build pd with tidb-dashboard:

`replace github.com/pingcap/tidb-dashboard v0.0.0-20210716172320-2226872e3296 => ../tidb-dashboard
`

I use the master branch code with both pd and tidb-dashboard.

**What did you see instead?**

pd meets a panic:

`[2021/08/05 13:08:28.960 +00:00] [FATAL] [log.go:293] [panic] [recover={}] [stack="github.com/tikv/pd/pkg/logutil.LogPanic\n\t/pingcap/pd/pkg/logutil/log.go:293\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:965\nruntime.panicdottypeE\n\t/usr/local/go/src/runtime/iface.go:261\ngithub.com/pingcap/tidb-dashboard/pkg/utils/distro.Data\n\t/pingcap/tidb-dashboard/pkg/utils/distro/distro.go:30\ngithub.com/pingcap/tidb-dashboard/pkg/utils/version.Print\n\t/pingcap/tidb-dashboard/pkg/utils/version/version.go:44\ngithub.com/pingcap/tidb-dashboard/pkg/apiserver.(*Service).Start\n\t/pingcap/tidb-dashboard/pkg/apiserver/apiserver.go:171\ngithub.com/tikv/pd/pkg/dashboard/adapter.(*Manager).startService\n\t/pingcap/pd/pkg/dashboard/adapter/manager.go:201\ngithub.com/tikv/pd/pkg/dashboard/adapter.(*Manager).checkAddress\n\t/pingcap/pd/pkg/dashboard/adapter/manager.go:151\ngithub.com/tikv/pd/pkg/dashboard/adapter.(*Manager).serviceLoop\n\t/pingcap/pd/pkg/dashboard/adapter/manager.go:90"]`

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

I use the master branch code of tidb-dashboard at first, and the same issue can be triggered in v2021.07.23.1.

**Comment by shhdgit** [comment]
Looks like I need a readonly fallback for distro infos.
Thanks for your feedback.
