### ISSUE TITLE
How does sql user authentication work

### ISSUE THREAD

**Issue by pupillord** [pingcap/tidb-dashboard#991]
When I login to the Dashboard using SQL user authntication, is the autehntication request sent directly to TiDB Server or forwarded to PD?

User verification process is eventually done on TiDB server, so which communication protocol was used to send info to TiDB server? HTTP, gRPC, MySQL or something else?

Lastly, where can I find the relevant code for TiDB-dashboard?

**Comment by breeswish** [comment]
If you have more questions, feel free to leave comments.
