### ISSUE TITLE
Add example to use Auth0 as sso login option in the doc

### ISSUE THREAD

**Issue by baurine** [pingcap/tidb-dashboard#993]

**Comment by breeswish** [comment]
I think Auth0 is compatible with OIDC SSO?

**Comment by baurine** [comment]
Sorry, I didn't write the title explicit enough, I mean add the example in the doc about how to use Auth0 as the OIDC provider.

**Comment by baurine** [comment]
PR: https://github.com/pingcap/docs-cn/pull/7093
